// Unit tests for `src/provider/segment.ts`.
//
// `resolveConversationSegment` walks the message history tail-first
// looking for a valid replay marker on the most recent assistant
// turn. The result feeds the upstream prompt cache key — a
// regression here would either break cross-conversation thinking
// replay or fragment the cache.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as vscode from 'vscode';

import { resolveConversationSegment } from '../src/provider/segment.js';

function userMessage(text: string): vscode.LanguageModelChatRequestMessage {
	return {
		role: vscode.LanguageModelChatMessageRole.User,
		content: [{ value: text } as unknown as vscode.LanguageModelTextPart],
	};
}

function assistantTextMessage(text: string): vscode.LanguageModelChatRequestMessage {
	return {
		role: vscode.LanguageModelChatMessageRole.Assistant,
		content: [{ value: text } as unknown as vscode.LanguageModelTextPart],
	};
}

function assistantWithMarker(
	segmentId: string,
	...leading: vscode.LanguageModelChatRequestMessage['content']
): vscode.LanguageModelChatRequestMessage {
	// The modern json-base64url marker format does NOT carry a
	// segmentId — it just encodes thinking blocks. The
	// segmentId is generated by `resolveConversationSegment`
	// itself when the marker is `valid` (see
	// `provider/replay/markers.ts`). To test the
	// "markerFound, segmentId reused" path we must use the
	// legacy raw-UUID format: `minimax-vscode\<uuid>`. The
	// parser recognises both.
	const markerBytes = new TextEncoder().encode(`minimax-vscode\\${segmentId}`);
	const part = new vscode.LanguageModelDataPart(markerBytes, 'minimax_marker');
	const content: vscode.LanguageModelChatRequestMessage['content'] = [
		...leading,
		part as unknown as vscode.LanguageModelContentPart,
	];
	return { role: vscode.LanguageModelChatMessageRole.Assistant, content };
}

test('resolveConversationSegment: empty history → new UUID, reason markerMissing', () => {
	const seg = resolveConversationSegment([]);
	assert.match(seg.segmentId, /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
	assert.equal(seg.reason, 'markerMissing');
});

test('resolveConversationSegment: only user messages → markerMissing', () => {
	const seg = resolveConversationSegment([userMessage('hi'), userMessage('again')]);
	assert.equal(seg.reason, 'markerMissing');
	assert.match(seg.segmentId, /^[0-9a-f-]{36}$/);
});

test('resolveConversationSegment: assistant message with a valid marker → markerFound, segmentId reused', () => {
	const id = '12345678-90ab-cdef-1234-567890abcdef';
	const seg = resolveConversationSegment([
		userMessage('hi'),
		assistantWithMarker(id, { value: 'reply' } as unknown as vscode.LanguageModelTextPart),
	]);
	assert.equal(seg.segmentId, id);
	assert.equal(seg.reason, 'markerFound');
	assert.equal(seg.markerMessageIndex, 1);
	assert.equal(seg.markerPartIndex, 1);
});

test('resolveConversationSegment: walks tail-first (latest assistant marker wins)', () => {
	const older = 'aaaaaaaa-1111-2222-3333-444455556666';
	const newer = 'bbbbbbbb-1111-2222-3333-444455556666';
	const seg = resolveConversationSegment([
		assistantWithMarker(older),
		userMessage('mid'),
		assistantWithMarker(newer),
	]);
	assert.equal(seg.segmentId, newer);
	assert.equal(seg.markerMessageIndex, 2);
});

test('resolveConversationSegment: assistant message with an invalid marker → no marker recognised, falls back to markerMissing + new UUID', () => {
	const bad = new vscode.LanguageModelDataPart(
		new TextEncoder().encode('not-a-marker'),
		'minimax_marker',
	);
	const seg = resolveConversationSegment([
		userMessage('hi'),
		{
			role: vscode.LanguageModelChatMessageRole.Assistant,
			content: [bad as unknown as vscode.LanguageModelContentPart],
		},
	]);
	// `parseReplayMarkerPart` now returns `undefined` for invalid
	// payloads, so `resolveConversationSegment` doesn't surface a
	// `markerInvalid` reason — the marker is just not found.
	assert.equal(seg.reason, 'markerMissing');
	assert.match(seg.segmentId, /^[0-9a-f-]{36}$/);
	assert.equal(seg.markerMessageIndex, undefined);
});

test('resolveConversationSegment: text-only assistant messages (no marker) → markerMissing', () => {
	const seg = resolveConversationSegment([
		userMessage('hi'),
		assistantTextMessage('plain reply'),
		userMessage('again'),
		assistantTextMessage('still no marker'),
	]);
	assert.equal(seg.reason, 'markerMissing');
	assert.equal(seg.markerMessageIndex, undefined);
});
